-- assigns roles to user accounts for Kohana version of Onestop.

-- clean out all onestop roles before inserting
DELETE FROM USTX.STAFF_ROLES WHERE ROLE_CODE IN ('UST_PI', 'UST_FIN', 'USTX_USER', 'UST_LUST', 'USTX_ADMIN');
/
-- permanently delete roles which arent used by neither CAF nor Onestop
DELETE FROM USTX.ROLES WHERE CODE IN ('USTX_USER', 'UST_LUST', 'USTX_ADMIN');
/

-- finance users

INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('MLE', 'UST_FIN');
--Bertha
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('BA', 'UST_FIN');
--Delia
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('DF', 'UST_FIN');
--Dana
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('DAB', 'UST_FIN');


-- inspection users

--INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('MLE2', 'UST_PI');

--Dan Lopez
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('DL', 'UST_PI');

--Keith Chavez
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('KJC', 'UST_PI');

--Bart Butler
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('BBU', 'UST_PI');

--Tom Gray
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('TG', 'UST_PI');

--Bob Bouren
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('RTB', 'UST_PI');

--Joe Godwin
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('JG', 'UST_PI');

--Lowell Watkins
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('LWA', 'UST_PI');

--Adrian Jaramillo
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('AJ', 'UST_PI');

--Elmer Smith
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('ES', 'UST_PI');

--Kal Martin
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('KWM', 'UST_PI');

--Tom Collins
INSERT INTO USTX.STAFF_ROLES (STAFF_CODE, ROLE_CODE) VALUES ('TC', 'UST_PI');

commit;
/