-- *** by DBA ***
GRANT CREATE SESSION TO ONESTOP_ROLE;

-- *** by USTX ***   
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.CITIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.COUNTIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.CSED_SSN TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.EXCEPTIONS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FACILITIES_MVW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FACILITY_HISTORY TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FACILITY_HISTORY_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FACILITY_INSPECTION_CONTACT TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FEE_SUMMARY TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FILL_MATERIAL TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FINANCIAL_METHODS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FINANCIAL_PROVIDERS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FINANCIAL_RESPONSIBILITIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FISCAL_YEARS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.HOLD_PERMITS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INSPECTIONS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INSPECTION_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INVOICES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INVOICE_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INVOICE_DETAIL TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INVOICE_DETAIL_FACILITIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.NOTICES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.NOTICE_DETAIL_FACILITIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OPERATORS_MVW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNERS_MVW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNER_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNER_COMMENTS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNER_WAIVERS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.PENALTIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.PENALTY_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.PERMITS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.QA_SETUP TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.ROLES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.STAFF TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.STAFF_ROLES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANKS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_DETAILS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_DETAIL_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_FILL_MATERIAL_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_HISTORY TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_HISTORY_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_INFO_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_OPERATOR_HISTORY TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_STATUS_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TRANSACTIONS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TRANSACTION_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_CONTROL TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_FACILITIES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_LOG TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_OWNERS TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_REF_CODES TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_ROLE_PRIVS TO ONESTOP_ROLE;

--views
--invalid GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.CITIES_VIEW TO ONESTOP_ROLE;
--invalid GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.COUNTIES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FACILITIES_MVW_VIEW TO ONESTOP_ROLE;
--invalid GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.FACILITY_TANK_HISTORY_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INSPECTION_CODES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.INSPECTIONS_VIEW TO ONESTOP_ROLE;
GRANT SELECT ON USTX.LUST_SL_CON_AMEND_VIEW TO ONESTOP_ROLE;  --accesses LUST tables
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.NOTICE_DETAIL_FAC_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.NOTICES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OPERATORS_MVW_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNER_CODES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNER_PAYMENTS_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNER_TRANSACTIONS_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.OWNERS_MVW_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.PENALTIES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.PENALTY_CODES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_DETAIL_CODES_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_DETAILS_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_DETAILS_VW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_HISTORY_CODES_VW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_HISTORY_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANK_HISTORY_VW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.TANKS_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_FACILITIES_VIEW TO ONESTOP_ROLE;
--invalid GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_LOCATIONS_MVW TO ONESTOP_ROLE;
--invalid GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_LOCATIONS_MVW_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.UST_OWNERS_VIEW TO ONESTOP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON USTX.V_FINANCIAL_RESPONSIBILITIES TO ONESTOP_ROLE;

-- *** by LUST *** 
GRANT SELECT ON LUST.LUST_RELEASES_MVW TO ONESTOP_ROLE;
GRANT SELECT ON LUST.LUST_STATUS_MVW TO ONESTOP_ROLE;
GRANT SELECT ON LUST.CG_REF_CODES TO ONESTOP_ROLE;

commit;
/